name: 2023_10_Vereinspräsentation_TUIlmenau_WS2324

on:
  push:
    branches:
      - main
    paths:
      - "2023_10_Vereinspräsentation_TUIlmenau_WS2324/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: xu-cheng/latex-action@v3
        with:
          working_directory: 2023_10_Vereinspräsentation_TUIlmenau_WS2324
          root_file: 2023_10_Vereinspräsentation_TUIlmenau_WS2324.tex

      - name: Build PDF
        run: |
          cd 2023_10_Vereinspräsentation_TUIlmenau_WS2324
          cp 2023_10_Vereinspräsentation_TUIlmenau_WS2324.pdf ../ISV_2023_10_Vereinspräsentation_TUIlmenau_WS2324.pdf
          cd ..

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 2023_10_Vereinspräsentation_TUIlmenau_WS2324
          path: ISV_2023_10_Vereinspräsentation_TUIlmenau_WS2324.pdf

      - name: Install WebDAV client
        run: sudo apt-get install -y davfs2

      - name: Upload zur ISV Cloud
        run: |
          EXTCLOUD_URL="${{ secrets.ISV_WEBDAV_BASE }}/${{ secrets.ISV_WEBDAV_PATH }}/"
          USERNAME="${{ secrets.ISV_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ISV_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2023_10_Vereinspräsentation_TUIlmenau_WS2324.pdf"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$EXTCLOUD_URL")


          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
           echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
           exit 1
          fi

      - name: Upload zur ESKOPP Cloud
        run: |
          EXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH }}/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2023_10_Vereinspräsentation_TUIlmenau_WS2324.pdf"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$EXTCLOUD_URL")


          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
           echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
           exit 1
          fi

      - name: Upload zur ISV Cloud Event
        run: |
          EXTCLOUD_URL="${{ secrets.ISV_WEBDAV_BASE }}/${{ secrets.ISV_WEBDAV_PATH_EVENT }}/2023_10_Vereinspräsentation_TUIlmenau_WS2324/"
          USERNAME="${{ secrets.ISV_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ISV_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2023_10_Vereinspräsentation_TUIlmenau_WS2324.pdf"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$EXTCLOUD_URL")


          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
           echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
           exit 1
          fi

      - name: Upload zur ESKOPP Cloud Event
        run: |
          EXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH_EVENT }}/2023_10_Vereinspräsentation_TUIlmenau_WS2324/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2023_10_Vereinspräsentation_TUIlmenau_WS2324.pdf"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$EXTCLOUD_URL")


          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
           echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
           exit 1
          fi

      - name: Upload zur ESKOPP Latex
        run: |
          EXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH_PUB }}/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2023_10_Vereinspräsentation_TUIlmenau_WS2324.pdf"

          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$EXTCLOUD_URL")


          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
           echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
           exit 1
          fi

      - name: Git Clean
        run: |
          git clean -fX
