name: 2023_08_Familienfest

on:
  push:
    branches:
      - main
    paths:
      - "2023_08_Familienfest/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up LaTeX
        run: |
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y texlive-fonts-recommended
          sudo apt-get install -y texlive-publishers
          sudo apt-get install -y texlive-science
          sudo apt-get install -y texlive-pstricks
          sudo apt-get install -y texlive-pictures
          sudo apt-get install -y texlive-metapost
          sudo apt-get install -y texlive-music
          sudo apt-get install -y texlive-xetex
          sudo apt-get install -y texlive-luatex
          sudo apt-get install -y texlive-games
          sudo apt-get install -y tree

      - name: Build PDFs
        run: |
          cd 2023_08_Familienfest
          pdflatex -interaction=nonstopmode -halt-on-error 2023_08_Familienfest.tex
          ls -aril
          cp 2023_08_Familienfest.pdf ../ISV_2023_08_Familienfest.pdf
          cd ..

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: 2023_08_Familienfest
          path: ISV_2023_08_Familienfest.pdf

      - name: Install WebDAV client
        run: sudo apt-get install -y davfs2

      - name: File Tree
        run: tree

      - name: Upload zur ISV Cloud
        run: |
          EXTCLOUD_URL="${{ secrets.ISV_WEBDAV_BASE }}/${{ secrets.ISV_WEBDAV_PATH }}/"
          USERNAME="${{ secrets.ISV_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ISV_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2023_08_Familienfest.pdf"
          
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$EXTCLOUD_URL")
      
          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            case $HTTP_STATUS in
              400)
                echo "Fehlerhafter Request. Bitte überprüfen Sie die Anfrageparameter."
                ;;
              401)
                echo "Authentifizierung fehlgeschlagen. Bitte überprüfen Sie die Zugangsdaten."
                ;;
              403)
                echo "Zugriff verweigert. Stellen Sie sicher, dass Sie die erforderlichen Berechtigungen haben."
                ;;
              404)
                echo "Die Nextcloud-URL oder der angegebene Ordner existiert nicht."
                ;;
              *)
                echo "Fehler beim Hochladen/Aktualisieren der PDF-Datei. Serverantwort-Statuscode: $HTTP_STATUS"
                exit 1  # Workflow fehlschlagen lassen
                ;;
            esac
          fi
      
      - name: Upload zur ESKOPP Cloud
        run: |
          EXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH }}/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2023_08_Familienfest.pdf"
          
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$EXTCLOUD_URL")
      
          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            case $HTTP_STATUS in
              400)
                echo "Fehlerhafter Request. Bitte überprüfen Sie die Anfrageparameter."
                ;;
              401)
                echo "Authentifizierung fehlgeschlagen. Bitte überprüfen Sie die Zugangsdaten."
                ;;
              403)
                echo "Zugriff verweigert. Stellen Sie sicher, dass Sie die erforderlichen Berechtigungen haben."
                ;;
              404)
                echo "Die Nextcloud-URL oder der angegebene Ordner existiert nicht."
                ;;
              *)
                echo "Fehler beim Hochladen/Aktualisieren der PDF-Datei. Serverantwort-Statuscode: $HTTP_STATUS"
                exit 1  # Workflow fehlschlagen lassen
                ;;
            esac
          fi
      
      - name: Upload zur ISV Cloud Event
        run: |
          EXTCLOUD_URL="${{ secrets.ISV_WEBDAV_BASE }}/${{ secrets.ISV_WEBDAV_PATH_EVENT }}/2023_08_Familienfest/"
          USERNAME="${{ secrets.ISV_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ISV_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2023_08_Familienfest.pdf"
          
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$EXTCLOUD_URL")
      
          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            case $HTTP_STATUS in
              400)
                echo "Fehlerhafter Request. Bitte überprüfen Sie die Anfrageparameter."
                ;;
              401)
                echo "Authentifizierung fehlgeschlagen. Bitte überprüfen Sie die Zugangsdaten."
                ;;
              403)
                echo "Zugriff verweigert. Stellen Sie sicher, dass Sie die erforderlichen Berechtigungen haben."
                ;;
              404)
                echo "Die Nextcloud-URL oder der angegebene Ordner existiert nicht."
                ;;
              *)
                echo "Fehler beim Hochladen/Aktualisieren der PDF-Datei. Serverantwort-Statuscode: $HTTP_STATUS"
                exit 1  # Workflow fehlschlagen lassen
                ;;
            esac
          fi
      
      - name: Upload zur ESKOPP Cloud Event
        run: |
          EXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH_EVENT }}/2023_08_Familienfest/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2023_08_Familienfest.pdf"
          
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$EXTCLOUD_URL")
      
          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            case $HTTP_STATUS in
              400)
                echo "Fehlerhafter Request. Bitte überprüfen Sie die Anfrageparameter."
                ;;
              401)
                echo "Authentifizierung fehlgeschlagen. Bitte überprüfen Sie die Zugangsdaten."
                ;;
              403)
                echo "Zugriff verweigert. Stellen Sie sicher, dass Sie die erforderlichen Berechtigungen haben."
                ;;
              404)
                echo "Die Nextcloud-URL oder der angegebene Ordner existiert nicht."
                ;;
              *)
                echo "Fehler beim Hochladen/Aktualisieren der PDF-Datei. Serverantwort-Statuscode: $HTTP_STATUS"
                exit 1  # Workflow fehlschlagen lassen
                ;;
            esac
          fi
      
      - name: Upload zur ESKOPP Latex
        run: |
          EXTCLOUD_URL="${{ secrets.ESKOPP_WEBDAV_BASE }}/${{ secrets.ESKOPP_WEBDAV_PATH_PUB }}/"
          USERNAME="${{ secrets.ESKOPP_WEBDAV_USER }}"
          PASSWORD="${{ secrets.ESKOPP_WEBDAV_PASSWORD }}"
          PDF_FILE="ISV_2023_08_Familienfest.pdf"
          
          HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -u "$USERNAME:$PASSWORD" -T "$PDF_FILE" "$EXTCLOUD_URL")
      
          if [ $HTTP_STATUS -eq 201 ] || [ $HTTP_STATUS -eq 204 ]; then
            echo "PDF-Datei wurde erfolgreich hochgeladen oder aktualisiert."
          else
            case $HTTP_STATUS in
              400)
                echo "Fehlerhafter Request. Bitte überprüfen Sie die Anfrageparameter."
                ;;
              401)
                echo "Authentifizierung fehlgeschlagen. Bitte überprüfen Sie die Zugangsdaten."
                ;;
              403)
                echo "Zugriff verweigert. Stellen Sie sicher, dass Sie die erforderlichen Berechtigungen haben."
                ;;
              404)
                echo "Die Nextcloud-URL oder der angegebene Ordner existiert nicht."
                ;;
              *)
                echo "Fehler beim Hochladen/Aktualisieren der PDF-Datei. Serverantwort-Statuscode: $HTTP_STATUS"
                exit 1  # Workflow fehlschlagen lassen
                ;;
            esac
          fi

      - name: Git Clean
        run: |
            git clean -fX        